"""Add file support to wikis

Revision ID: 25f1131f0ddf
Revises: 4b49551b705e
Create Date: 2026-06-25 15:10:26.184975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25f1131f0ddf'
down_revision: Union[str, Sequence[str], None] = '4b49551b705e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wiki_pages', sa.Column('doc_type', sa.String(), nullable=True))
    op.add_column('wiki_pages', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wiki_pages', 'file_url')
    op.drop_column('wiki_pages', 'doc_type')
    # ### end Alembic commands ###
