"""Added first and last name separately

Revision ID: 273e8dd09703
Revises: 43d0cbafa916
Create Date: 2026-06-25 14:13:41.547076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273e8dd09703'
down_revision: Union[str, Sequence[str], None] = '43d0cbafa916'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('type', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('link', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('notifications', 'link')
    op.drop_column('notifications', 'type')
    # ### end Alembic commands ###
