"""Project history in activity.

Revision ID: 3742b145e064
Revises: 34c52e6e1df5
Create Date: 2026-07-13 15:37:17.370012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3742b145e064'
down_revision: Union[str, Sequence[str], None] = '34c52e6e1df5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_created_by_id'), 'tasks', ['created_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_created_by_id'), table_name='tasks')
    # ### end Alembic commands ###
