"""add project key and task counter

Revision ID: 40bfc2dfcbd2
Revises: 28de28e11354
Create Date: 2026-07-03 15:24:02.677820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40bfc2dfcbd2'
down_revision: Union[str, Sequence[str], None] = '28de28e11354'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_key', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('task_counter', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_project_key'), 'projects', ['project_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_project_key'), table_name='projects')
    op.drop_column('projects', 'task_counter')
    op.drop_column('projects', 'project_key')
    # ### end Alembic commands ###
