"""Rename super admin to owner

Revision ID: 476e41171265
Revises: 5fc0ba5fe681
Create Date: 2026-07-16 16:16:01.835708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '476e41171265'
down_revision: Union[str, Sequence[str], None] = '5fc0ba5fe681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('is_owner', sa.Boolean(), nullable=True))
    op.drop_column('invitations', 'is_super_admin')
    op.add_column('users', sa.Column('is_owner', sa.Boolean(), nullable=True))
    op.drop_column('users', 'is_super_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_super_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('users', 'is_owner')
    op.add_column('invitations', sa.Column('is_super_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('invitations', 'is_owner')
    # ### end Alembic commands ###
