"""Add file support to Messages

Revision ID: 4a2e71d76de9
Revises: f10fd4b93288
Create Date: 2026-06-25 20:25:52.083286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a2e71d76de9'
down_revision: Union[str, Sequence[str], None] = 'f10fd4b93288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('file_url', sa.String(), nullable=True))
    op.add_column('messages', sa.Column('file_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'file_name')
    op.drop_column('messages', 'file_url')
    # ### end Alembic commands ###
