"""Add project_id to comments

Revision ID: 4b49551b705e
Revises: 273e8dd09703
Create Date: 2026-06-25 14:27:50.216520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b49551b705e'
down_revision: Union[str, Sequence[str], None] = '273e8dd09703'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'comments', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_column('comments', 'project_id')
    # ### end Alembic commands ###
