"""Add full_name to Invitation

Revision ID: 66642ccdd9f5
Revises: 9f4bf0e94871
Create Date: 2026-07-13 18:40:08.161461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66642ccdd9f5'
down_revision: Union[str, Sequence[str], None] = '9f4bf0e94871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('full_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'full_name')
    # ### end Alembic commands ###
