"""Add company_role to User

Revision ID: 7efbebb55901
Revises: 25f1131f0ddf
Create Date: 2026-06-25 15:29:21.229593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7efbebb55901'
down_revision: Union[str, Sequence[str], None] = '25f1131f0ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company_role', sa.String(), nullable=True))
    op.drop_column('users', 'department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'company_role')
    # ### end Alembic commands ###
