"""tables for board customization

Revision ID: 82f73bb6ef17
Revises: 0671be66474f
Create Date: 2026-07-03 13:02:04.796879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f73bb6ef17'
down_revision: Union[str, Sequence[str], None] = '0671be66474f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('board_type', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('board_columns', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'board_columns')
    op.drop_column('projects', 'board_type')
    # ### end Alembic commands ###
