"""add task visibility

Revision ID: 8e2f1a9b3c4d
Revises: 7de5941ca8aa
Create Date: 2026-07-17 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e2f1a9b3c4d'
down_revision: Union[str, Sequence[str], None] = '7de5941ca8aa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('task_visibility', sa.String(), server_default='everyone', nullable=True))
    op.add_column('projects', sa.Column('task_viewers', sa.JSON(), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'task_viewers')
    op.drop_column('projects', 'task_visibility')
    # ### end Alembic commands ###
