"""Remove unique constraint from account email

Revision ID: 982820253089
Revises: fa7ad0323585
Create Date: 2026-07-24 15:37:43.423645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982820253089'
down_revision: Union[str, Sequence[str], None] = 'fa7ad0323585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    # ### end Alembic commands ###
