"""added link for tasks to reference respective doc.

Revision ID: aa35cd363756
Revises: ddf052eb9937
Create Date: 2026-06-26 17:30:40.953318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa35cd363756'
down_revision: Union[str, Sequence[str], None] = 'ddf052eb9937'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('source_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'source_link')
    # ### end Alembic commands ###
