"""Add issue tracking fields to tasks

Revision ID: bb9c5d5719cc
Revises: cce5330db18d
Create Date: 2026-06-23 17:04:38.862837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb9c5d5719cc'
down_revision: Union[str, Sequence[str], None] = 'cce5330db18d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('issue_type', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('severity', sa.String(), nullable=True))
    op.add_column('tasks', sa.Column('ticket_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_tasks_ticket_id'), 'tasks', ['ticket_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_ticket_id'), table_name='tasks')
    op.drop_column('tasks', 'ticket_id')
    op.drop_column('tasks', 'severity')
    op.drop_column('tasks', 'issue_type')
    # ### end Alembic commands ###
