"""Add role to invite

Revision ID: cce5330db18d
Revises: 36ec1cb396ce
Create Date: 2026-06-22 13:25:23.474972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cce5330db18d'
down_revision: Union[str, Sequence[str], None] = '36ec1cb396ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invitations', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invitations', 'role')
    # ### end Alembic commands ###
