"""added subtasks

Revision ID: 4d9b9675b53e
Revises: b09435d543bf
Create Date: 2026-07-13 19:59:08.459682

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9b9675b53e'
down_revision: Union[str, Sequence[str], None] = 'b09435d543bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_integrations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('access_token', sa.String(), nullable=True),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('workspace_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_integrations_id'), 'app_integrations', ['id'], unique=False)
    op.create_index(op.f('ix_app_integrations_provider'), 'app_integrations', ['provider'], unique=False)
    op.create_index(op.f('ix_app_integrations_workspace_id'), 'app_integrations', ['workspace_id'], unique=False)
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('target_name', sa.String(), nullable=True),
    sa.Column('target_type', sa.String(), nullable=True),
    sa.Column('ticket_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activities_id'), 'activities', ['id'], unique=False)
    op.create_index(op.f('ix_activities_project_id'), 'activities', ['project_id'], unique=False)
    op.create_index(op.f('ix_activities_user_id'), 'activities', ['user_id'], unique=False)
    op.create_table('subtasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subtasks_id'), 'subtasks', ['id'], unique=False)
    op.create_index(op.f('ix_subtasks_task_id'), 'subtasks', ['task_id'], unique=False)
    op.create_table('work_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hours_spent', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_logs_id'), 'work_logs', ['id'], unique=False)
    op.create_index(op.f('ix_work_logs_task_id'), 'work_logs', ['task_id'], unique=False)
    op.create_index(op.f('ix_work_logs_user_id'), 'work_logs', ['user_id'], unique=False)
    op.add_column('invitations', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('notifications', sa.Column('workspace_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notifications', 'workspaces', ['workspace_id'], ['id'])
    op.add_column('tasks', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tasks_created_by_id'), 'tasks', ['created_by_id'], unique=False)
    op.create_foreign_key(None, 'tasks', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_index(op.f('ix_tasks_created_by_id'), table_name='tasks')
    op.drop_column('tasks', 'created_by_id')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'workspace_id')
    op.drop_column('invitations', 'full_name')
    op.drop_index(op.f('ix_work_logs_user_id'), table_name='work_logs')
    op.drop_index(op.f('ix_work_logs_task_id'), table_name='work_logs')
    op.drop_index(op.f('ix_work_logs_id'), table_name='work_logs')
    op.drop_table('work_logs')
    op.drop_index(op.f('ix_subtasks_task_id'), table_name='subtasks')
    op.drop_index(op.f('ix_subtasks_id'), table_name='subtasks')
    op.drop_table('subtasks')
    op.drop_index(op.f('ix_activities_user_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_project_id'), table_name='activities')
    op.drop_index(op.f('ix_activities_id'), table_name='activities')
    op.drop_table('activities')
    op.drop_index(op.f('ix_app_integrations_workspace_id'), table_name='app_integrations')
    op.drop_index(op.f('ix_app_integrations_provider'), table_name='app_integrations')
    op.drop_index(op.f('ix_app_integrations_id'), table_name='app_integrations')
    op.drop_table('app_integrations')
    # ### end Alembic commands ###
