"""add organization management

Revision ID: fa7ad0323585
Revises: 4d9b9675b53e
Create Date: 2026-07-20 15:55:36.516386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa7ad0323585'
down_revision: Union[str, Sequence[str], None] = '4d9b9675b53e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    op.create_index(op.f('ix_accounts_name'), 'accounts', ['name'], unique=False)
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('otp_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_email'), 'otps', ['email'], unique=False)
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_devices_device_id'), 'user_devices', ['device_id'], unique=False)
    op.create_index(op.f('ix_user_devices_id'), 'user_devices', ['id'], unique=False)
    op.create_index(op.f('ix_user_devices_user_id'), 'user_devices', ['user_id'], unique=False)
    op.add_column('invitations', sa.Column('is_owner', sa.Boolean(), nullable=True))
    op.add_column('invitations', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_invitations_project_id'), 'invitations', ['project_id'], unique=False)
    op.create_foreign_key(None, 'invitations', 'projects', ['project_id'], ['id'])
    op.add_column('projects', sa.Column('task_visibility', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('task_viewers', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_owner', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('account_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_account_id'), 'users', ['account_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_foreign_key(None, 'users', 'accounts', ['account_id'], ['id'])
    op.add_column('workspaces', sa.Column('account_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_workspaces_owner_id'), table_name='workspaces')
    op.create_index(op.f('ix_workspaces_account_id'), 'workspaces', ['account_id'], unique=False)
    op.drop_constraint(op.f('workspaces_owner_id_fkey'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'accounts', ['account_id'], ['id'])
    op.drop_column('workspaces', 'owner_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workspaces', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('workspaces_owner_id_fkey'), 'workspaces', 'users', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_workspaces_account_id'), table_name='workspaces')
    op.create_index(op.f('ix_workspaces_owner_id'), 'workspaces', ['owner_id'], unique=False)
    op.drop_column('workspaces', 'account_id')
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_account_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'account_id')
    op.drop_column('users', 'is_owner')
    op.drop_column('users', 'username')
    op.drop_column('projects', 'task_viewers')
    op.drop_column('projects', 'task_visibility')
    op.drop_constraint(None, 'invitations', type_='foreignkey')
    op.drop_index(op.f('ix_invitations_project_id'), table_name='invitations')
    op.drop_column('invitations', 'project_id')
    op.drop_column('invitations', 'is_owner')
    op.drop_index(op.f('ix_user_devices_user_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_id'), table_name='user_devices')
    op.drop_index(op.f('ix_user_devices_device_id'), table_name='user_devices')
    op.drop_table('user_devices')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_email'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('ix_accounts_name'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
